version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo installing maven...
      - yum update 
      - yum install -y maven
  build:
    commands:
      - echo Build started on `date`
       - ls -ltr
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/main-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
cache:
    paths:
    - '/root/.m2/**/*'
